# Generated by Django 3.0.5 on 2020-05-08 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_pg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite_form',
            name='invitees',
        ),
        migrations.AddField(
            model_name='invite_form',
            name='invitees',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
