# Generated by Django 3.0.5 on 2020-05-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_pg', '0002_auto_20200508_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUsers',
        ),
    ]
