# Generated by Django 3.0.5 on 2020-05-10 15:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login_pg', '0003_delete_myusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite_form',
            name='invitees',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'kesha'), (1, 'sweta'), (2, 'kishor'), (3, 'priyav')], max_length=7),
        ),
    ]
