# Generated by Django 3.0.5 on 2020-05-11 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_pg', '0005_auto_20200510_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite_form',
            name='invitees',
            field=models.ForeignKey(error_messages={'required': 'No record found!'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
