# Generated by Django 3.0.5 on 2020-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_pg', '0006_auto_20200511_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite_form',
            name='invitees',
            field=models.CharField(choices=[('kesha', 'kesha'), ('sweta', 'sweta'), ('kishor', 'kishor'), ('priyav', 'priyav')], max_length=50),
        ),
    ]
